In [1]:
import numpy as np
from scipy.optimize import least_squares
#from pandas import Series, DataFrame
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Qt5Agg')
%matplotlib qt5
#
# if pade.py is not in the current directory, set this path:
#
#import sys
#sys.path.append('../Python_libs')
from rac_aux import *

In [2]:
Angs2Bohr=1.8897259886
au2eV=27.211386027
au2cm=219474.63068
#
#  files in the current directory do not need the path name
#
#df = pd.read_csv("/home/thomas/Python/StabPlots/Stab_data/1D_a0.2_b0_c0.14/crossing_1.dat", delim_whitespace=True)
df = pd.read_csv("sb_rac.csv")
#df = pd.read_csv("crossing_1.dat", delim_whitespace=True)

plot_it=False
if plot_it:
    plt.cla()
    plt.plot(df.l.values, df.E1.values, 'o-')
    plt.plot(df.l.values, df.E2.values, 'o-')
    plt.plot(df.l.values, df.E3.values, 'o-')
    plt.show()
df[:5]

l        E1        E2        E3        E4
0  0.0  0.469219  1.365173  1.938043  3.271038
1  0.2  0.457846  1.314401  1.844238  3.242423
2  0.4  0.446073  1.251127  1.760926  3.215267
3  0.6  0.433754  1.173608  1.690292  3.189317
4  0.8  0.420648  1.082215  1.632448  3.164365

In [3]:
i_neg = np.argmin(abs(df.E1.values))
if df.E1[i_neg] > 0:
    i_neg += 1
ls = df.l.values[i_neg:]
print('N=',len(ls))
Es = df.E1.values[i_neg:]
if plot_it:
    plt.cla()
    plt.plot(df.l.values, df.E1.values, 'b-')
    plt.plot(df.l.values, df.E2.values, 'b-')
    plt.plot(df.l.values, df.E3.values, 'b-')
    plt.plot(ls, Es, 'o', color="orange")
    plt.show()

N= 89


In [4]:
k2s = -Es
ks  = np.sqrt(k2s)

In [5]:
# start params
E0 = linear_extra(ls,Es)
G0 = 0.2*E0
p0s=[ls[0]] + guess(E0, G0) + guess(5*E0,10*G0) + [10]
print(p0s)
print(chi2_gen(p0s, ks, k2s, ls, pade_42_lsq))

[2.4, 0.2704669890140844, 1.4666963639216455, 0.570916223186097, 3.29172828739109, 10]
91.97737298598086


In [ ]:
p31_opt = [2.40228618, 0.27139798, 1.28131923]

In [9]:
#
#  the derivative of [4,2] works
#

N=6

df1s = pade_gen_j_lsq(p0s, ks[-N:], k2s[-N:], ls[-N:], pade_42_lsq)
print("num grad:\n", df1s)

df2s = pade_42j_lsq(p0s, ks[-N:], k2s[-N:], ls[-N:])
print("ana grad:\n", df2s)

df1s-df2s

num grad:
 [[ 1.74837643  1.04410881  0.75117465  0.09132267  2.51127503 -0.83591303]
 [ 1.76700182  1.05049612  0.75106652  0.09173122  2.53837509 -0.84484744]
 [ 1.78563814  1.05684827  0.75095982  0.09213841  2.56549062 -0.85378705]
 [ 1.80428529  1.06316586  0.75085452  0.09254426  2.59262151 -0.86273183]
 [ 1.82294317  1.06944947  0.75075056  0.09294877  2.61976762 -0.87168173]
 [ 1.84161166  1.07569966  0.75064791  0.09335195  2.64692882 -0.88063669]]
ana grad:
 [[ 1.74837643  1.04410881  0.75117465  0.09132267  2.51127503 -0.83591303]
 [ 1.76700182  1.05049612  0.75106652  0.09173122  2.53837509 -0.84484744]
 [ 1.78563814  1.05684827  0.75095982  0.09213841  2.56549062 -0.85378705]
 [ 1.80428529  1.06316586  0.75085452  0.09254426  2.59262151 -0.86273183]
 [ 1.82294317  1.06944946  0.75075056  0.09294877  2.61976762 -0.87168173]
 [ 1.84161166  1.07569966  0.75064791  0.09335195  2.64692882 -0.88063669]]


array([[ 2.55742094e-11, -9.61775104e-11, -1.50029988e-11,
         1.48589724e-10,  2.43520759e-11, -1.73946413e-10],
       [ 4.35944614e-11,  3.38509221e-11, -1.00044417e-11,
         6.34104297e-11,  3.36499717e-11, -1.74612991e-10],
       [ 3.95663502e-11, -2.79354540e-10,  2.30918618e-11,
        -5.80744203e-11,  4.35611547e-11, -1.73104864e-10],
       [ 2.10509388e-11, -1.74722681e-10,  1.62903024e-12,
        -4.98261016e-11,  2.49289478e-11, -1.73846271e-10],
       [ 1.11315401e-11,  4.68280970e-11,  7.02327085e-12,
         3.31425026e-11,  1.03437259e-11, -1.75637505e-10],
       [ 5.27675681e-11, -1.21796573e-10, -3.92059718e-11,
        -2.14547394e-10, -2.19202434e-12, -1.75995996e-10]])

In [ ]:
# start params
E0 = linear_extra(ls,Es)
G0 = 0.2*E0
p0s=[ls[0]] + guess(E0, G0) + [10]
print(chi2_gen(p0s, ks, k2s, ls, pade_31))

In [10]:
#
#  test results of other minimizers wrt least squares
#
#p0s=res.x

print("Start parameters:",p0s)
print('Least squares, 2-point jac')
res = least_squares(pade_42_lsq, p0s, method='trf', jac='2-point', args=(ks, k2s, ls))
print("njev:",res.njev)
print("cost:",res.cost)
print("grad:",res.grad)
print("message:",res.message)
print("success:",res.success)
print("x:", res.x)
print('chi2 = %.3e' % (res.cost*2/len(ks)))
print("Er=%f,  Gamma=%f" % res_ene(res.x[1], res.x[2]))

Start parameters: [2.4, 0.2704669890140844, 1.4666963639216455, 0.570916223186097, 3.29172828739109, 10]
Least squares, 2-point jac
njev: 131
cost: 9.866093194892789e-07
grad: [-1.37223952e-09 -2.99601881e-10  3.21162522e-09 -4.88484981e-10
 -2.37046224e-09  2.13999556e-09]
message: `gtol` termination condition is satisfied.
success: True
x: [2.39193215 0.29644131 1.3187318  1.37364013 0.29655318 0.50789635]
chi2 = 2.217e-08
Er=1.731331,  Gamma=0.463547


In [12]:
print('Least squares, trust-region-reflective (default) with analytic jac')
res = least_squares(pade_42_lsq, p0s, method='trf', jac=pade_42j_lsq, args=(ks, k2s, ls))
print("njev:",res.njev)
print("cost:",res.cost)
print("grad:",res.grad)
print("message:",res.message)
print("success:",res.success)
print("x:", res.x)
print('chi2 = %.3e' % (res.cost*2/len(ks)))
print("Er=%f,  Gamma=%f" % res_ene(res.x[1], res.x[2]))

Least squares, trust-region-reflective (default) with analytic jac
njev: 131
cost: 9.86609319494982e-07
grad: [-4.57481781e-09 -3.39880384e-10  1.05237323e-08 -1.21449231e-09
 -7.96253595e-09  7.00631132e-09]
message: `ftol` termination condition is satisfied.
success: True
x: [2.39193215 0.29644125 1.31873181 1.3736413  0.29655369 0.50789712]
chi2 = 2.217e-08
Er=1.731331,  Gamma=0.463547


In [13]:
print('Least squares, Levenberg-Marquardt with analytic jac')
res = least_squares(pade_42_lsq, p0s, method='lm', jac=pade_42j_lsq, args=(ks, k2s, ls))
print("njev:",res.njev)
print("cost:",res.cost)
print("grad:",res.grad)
print("message:",res.message)
print("success:",res.success)
print("x:", res.x)
print('chi2 = %.3e' % (res.cost*2/len(ks)))
print("Er=%f,  Gamma=%f" % res_ene(res.x[1], res.x[2]))

Least squares, Levenberg-Marquardt with analytic jac
njev: 115
cost: 9.866093194961547e-07
grad: [-5.28932675e-09  3.93176228e-10  1.21678506e-08 -1.40517543e-09
 -9.20619615e-09  8.09953240e-09]
message: `ftol` termination condition is satisfied.
success: True
x: [ 2.39193215 -0.29644125  1.31873181  1.37364137  0.29655372  0.50789717]
chi2 = 2.217e-08
Er=1.731331,  Gamma=0.463547


In [15]:
print('Least squares, TRF with bounds')

bnds=([0,0,0, 0,0,0],[np.inf,np.inf,np.inf, np.inf,np.inf,np.inf])

res = least_squares(pade_42_lsq, p0s, jac=pade_42j_lsq, bounds=bnds, args=(ks, k2s, ls))
print("njev:",res.njev)
print("cost:",res.cost)
print("grad:",res.grad)
print("message:",res.message)
print("success:",res.success)
print("x:", res.x)
print('chi2 = %.3e' % (res.cost*2/len(ks)))
print("Er=%f,  Gamma=%f" % res_ene(res.x[1], res.x[2]))

Least squares, TRF with bounds
njev: 343
cost: 9.866093195006935e-07
grad: [-1.58867865e-08 -1.18401821e-09  3.65557322e-08 -4.23755071e-09
 -2.76539992e-08  2.42964954e-08]
message: `ftol` termination condition is satisfied.
success: True
x: [2.39193214 0.29644124 1.31873181 1.37364164 0.29655385 0.50789736]
chi2 = 2.217e-08
Er=1.731331,  Gamma=0.463547


In [ ]:
l0, a, b, d = res.x